# -*- mode: python; -*-

#
# Copyright (c) 2013 Juniper Networks, Inc. All rights reserved.
#

Import('BuildEnv')
env = BuildEnv.Clone()

base_path = '#src/contrail-analytics/tf-snmp-collector/'

mibs = Glob('mibs/*')

prouter_pkg = env.SandeshGenPy('prouter.sandesh', base_path + 'tf_snmp_collector/sandesh/', False)
snmp_collector_info_pkg = env.SandeshGenPy('snmp_collector_info.sandesh', base_path + 'tf_snmp_collector/sandesh/', False)
nodeinfo_pkg = env.SandeshGenPy('#src/contrail-common/base/sandesh/nodeinfo.sandesh', base_path + 'tf_snmp_collector/sandesh/', False)
cpuinfo_pkg = env.SandeshGenPy('#src/contrail-common/base/sandesh/cpuinfo.sandesh', base_path + 'tf_snmp_collector/sandesh/nodeinfo/', False)
process_info_pkg = env.SandeshGenPy('#src/contrail-common/base/sandesh/process_info.sandesh', base_path + 'tf_snmp_collector/sandesh/nodeinfo/', False)

sdist_depends = [prouter_pkg, snmp_collector_info_pkg, nodeinfo_pkg, cpuinfo_pkg, process_info_pkg]

if 'install' in BUILD_TARGETS:
    doc_files = []
    doc_files += env['ANALYTICS_DOC_FILES']
    doc_files += env.SandeshGenDoc('prouter.sandesh')
    doc_files += env.SandeshGenDoc('snmp_collector_info.sandesh')
    env.Alias('install', env.Install(
        env['INSTALL_DOC'] + '/../mibs/netsnmp', mibs))
    env.Alias('install', env.Install(
        env['INSTALL_MESSAGE_DOC'] + '/tf-snmp-collector/', doc_files))

sdist_gen = env.Command(
    '/pip/tf_snmp_collector-0.1.dev0-py3-none-any.whl', 'setup.py',
    'cd ' + Dir(base_path).path + ' && ' + 'python3 setup.py bdist_wheel --dist-dir /pip')
env.Depends(sdist_gen, sdist_depends)
env.Alias('install', sdist_gen)
