# -*- mode: python; -*-

#
# Copyright (c) 2013 Juniper Networks, Inc. All rights reserved.
#

Import('BuildEnv')
env = BuildEnv.Clone()

base_path = '#src/contrail-analytics/tf-topology/'

src_sandesh = env.SandeshGenPy('link.sandesh', base_path + 'tf_topology/sandesh/', False)
topology_info_pkg = env.SandeshGenPy('topology_info.sandesh', base_path + 'tf_topology/sandesh/', False)
cpuinfo_pkg = env.SandeshGenPy('#src/contrail-common/base/sandesh/cpuinfo.sandesh', base_path + 'tf_topology/sandesh/nodeinfo/', False)
process_info_pkg = env.SandeshGenPy('#src/contrail-common/base/sandesh/process_info.sandesh', base_path + 'tf_topology/sandesh/nodeinfo/', False)
nodeinfo_pkg = env.SandeshGenPy('#src/contrail-common/base/sandesh/nodeinfo.sandesh', base_path + 'tf_topology/sandesh/', False)
derived_stats_pkg = env.SandeshGenPy('#src/contrail-common/sandesh/library/common/derived_stats_results.sandesh', base_path + 'tf_topology/sandesh/analytics/', False)

sdist_depends = [nodeinfo_pkg, cpuinfo_pkg, process_info_pkg, src_sandesh, derived_stats_pkg, topology_info_pkg]

if 'install' in BUILD_TARGETS:
    doc_files = []
    doc_files += env['ANALYTICS_DOC_FILES']
    doc_files += env.SandeshGenDoc('link.sandesh')
    doc_files += env.SandeshGenDoc('topology_info.sandesh')
    env.Alias('install', env.Install(
        env['INSTALL_MESSAGE_DOC'] + '/tf-topology/', doc_files))

sdist_gen = env.Command(
    '/pip/tf_topology-0.1.dev0-py3-none-any.whl', 'setup.py',
    'cd ' + Dir(base_path).path + ' && ' + 'python3 setup.py bdist_wheel --dist-dir /pip')
env.Depends(sdist_gen, sdist_depends)
env.Alias('install', sdist_gen)
